---

#
# Tasks for ansible-gvm
#

- name: Include OS-Specific Variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define package list
  set_fact:
    gvm_packages: "{{ __gvm_packages | list }}"
  when: gvm_packages is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Fetch install script
  get_url: url=http://get.gvmtool.net/ dest=/tmp/gvm_installer.sh mode=0500 # sha256sum=fd8ac0bbf940f04606c578321a5bbc23d5c44b76

- name: Install GVM
  shell: /tmp/gvm_installer.sh | tee /tmp/gvm_install_log.txt

